### ISSUE TITLE
Implement/Finish Rebel Uprising Quest

### ISSUE THREAD

**Issue by CollinHerber** [hamzah-hayat/AdditionalQuests#6]
As of right now it's only reference in the Readme. 
This ticket is meant to serve as a reminder to start and finish this quest.

**Comment by hamzah-hayat** [comment]
Oops, duplicate entry in the README, this is actually already implemented as the Rebellion in {ISSUE_SETTLEMENT}! quest

**Comment by CollinHerber** [comment]
Resolved Here: https://github.com/hamzah-hayat/AdditionalQuests/commit/a07b79b6479691958f915212787b1b168cf14a9a
